version: '3.9'
services:
  db:
    image: postgres
    container_name: nekicard-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: neki123@
      POSTGRES_USER: nekicard
      POSTGRES_DB: nekicard
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - dev-network
  api:
    image: arawns/neki_card
    container_name: nekicard-api
    environment:
      APP_PROFILE: prod
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: nekicard
      DATABASE_USERNAME: nekicard
      DATABASE_PASSWORD: neki123@
    ports:
      - 8081:8080
    networks:
      - dev-network
    depends_on:
      - db

networks:
  dev-network:
    driver: bridge

volumes:
  postgres-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:\Volumes Docker'
