spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/nekicard}
    username: ${DATABASE_USERNAME:nekicard}
    password: ${DATABASE_PASSWORD:neki123@}
